trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

variables:
  buildConfiguration: 'Release'
  outputDirectory: '$(build.binariesDirectory)/$(buildConfiguration)'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '**/*.sln'

- task: XamarinAndroid@1
  inputs:
    projectFile: '**/FlutterSharp.Samples.Android.csproj'
    outputDirectory: '$(outputDirectory)'
    configuration: '$(buildConfiguration)'
    msbuildArguments: '/p:JavaSdkDirectory="$(JAVA_HOME)/" /p:AndroidNdkDirectory=$(ANDROID_NDK_HOME) /t:SignAndroidPackage /p:AndroidKeyStore=false' 

- task: NuGetCommand@2
  inputs:
    command: 'pack'
    packagesToPack: 'FlutterSharp.nuspec'
    versioningScheme: 'byBuildNumber'
    
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(outputDirectory)'
    ArtifactName: 'Output'
    publishLocation: 'Container'